"""Add income and life_expectancy columns

Revision ID: 63a6cb65fa0a
Revises: 3bfb94e477cb
Create Date: 2025-05-16 20:13:04.724801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a6cb65fa0a'
down_revision = '3bfb94e477cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income', sa.String(length=50), nullable=True))
        batch_op.drop_column('gdp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gdp', sa.FLOAT(), nullable=True))
        batch_op.drop_column('income')

    # ### end Alembic commands ###
