"""Initial migration

Revision ID: b1a5fd2a0a7b
Revises: d3b2a04d1074
Create Date: 2025-05-16 19:02:02.641516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a5fd2a0a7b'
down_revision = 'd3b2a04d1074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('covid_stat')
    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('covid_stat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
